{% set name = "nptyping" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ramonhagenaars/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: adc67bd533e3a24869a1b5715bb973f5a1e3920565b0f666e5cbf0c6200ee67f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - typish >=1.5.2

test:
  imports:
    - nptyping
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ramonhagenaars/nptyping
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Type hints for Numpy

  description: |
    nptyping.NDArray lets you define the shape and type of your numpy.ndarray.
  doc_url: https://github.com/ramonhagenaars/nptyping
  dev_url: https://github.com/ramonhagenaars/nptyping

extra:
  recipe-maintainers:
    - jan-janssen
