{% set name = "nptyping" %}
{% set version = "1.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ramonhagenaars/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e3edb227ec7882046d4b9a6f9c3c55fdfcb2299078b59072d537609bdb704816

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - typish >=1.5.2

test:
  imports:
    - nptyping
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ramonhagenaars/nptyping
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Type hints for Numpy

  description: |
    nptyping.NDArray lets you define the shape and type of your numpy.ndarray.
  doc_url: https://github.com/ramonhagenaars/nptyping
  dev_url: https://github.com/ramonhagenaars/nptyping

extra:
  recipe-maintainers:
    - jan-janssen
